MERGE INTO holidays (date, reason) KEY(date) VALUES ('2026-01-01', 'Año nuevo');
MERGE INTO holidays (date, reason) KEY(date) VALUES ('2026-02-16', 'Carnaval');
MERGE INTO holidays (date, reason) KEY(date) VALUES ('2026-02-17', 'Carnaval');
MERGE INTO holidays (date, reason) KEY(date) VALUES ('2026-03-23', 'Puente turístico no laborable');
MERGE INTO holidays (date, reason) KEY(date) VALUES ('2026-03-24', 'Día Nacional de la Memoria por la Verdad y la Justicia');
MERGE INTO holidays (date, reason) KEY(date) VALUES ('2026-04-02', 'Día del Veterano y de los Caídos en la Guerra de Malvinas');
MERGE INTO holidays (date, reason) KEY(date) VALUES ('2026-04-03', 'Viernes Santo');
MERGE INTO holidays (date, reason) KEY(date) VALUES ('2026-05-01', 'Día del Trabajador');
MERGE INTO holidays (date, reason) KEY(date) VALUES ('2026-05-25', 'Día de la Revolución de Mayo');
MERGE INTO holidays (date, reason) KEY(date) VALUES ('2026-06-15', 'Paso a la Inmortalidad del General Martín Güemes (17/6)');
MERGE INTO holidays (date, reason) KEY(date) VALUES ('2026-06-20', 'Paso a la Inmortalidad del General Manuel Belgrano');
MERGE INTO holidays (date, reason) KEY(date) VALUES ('2026-07-09', 'Día de la Independencia');
MERGE INTO holidays (date, reason) KEY(date) VALUES ('2026-07-10', 'Puente turístico no laborable');
MERGE INTO holidays (date, reason) KEY(date) VALUES ('2026-08-17', 'Paso a la Inmortalidad del Gral. José de San Martín');
MERGE INTO holidays (date, reason) KEY(date) VALUES ('2026-10-12', 'Día del Respeto a la Diversidad Cultural');
MERGE INTO holidays (date, reason) KEY(date) VALUES ('2026-11-23', 'Día de la Soberanía Nacional (20/11)');
MERGE INTO holidays (date, reason) KEY(date) VALUES ('2026-12-07', 'Puente turístico no laborable');
MERGE INTO holidays (date, reason) KEY(date) VALUES ('2026-12-08', 'Día de la Inmaculada Concepción de María');
MERGE INTO holidays (date, reason) KEY(date) VALUES ('2026-12-25', 'Navidad');